const ADD_TODO = 'ADD_TODO';
const DELETE_TODO = 'DELETE_TODO';
const SAVE_TODO = 'SAVE_TODO';
const TOGGLE_TODO = 'TOGGLE_TODO';
const TOGGLE_ALL_TODOS = 'TOGGLE_ALL_TODOS';
const CLEAR_COMPLETED = 'CLEAR_COMPLETED';
const CLEAR_ALL = 'CLEAR_ALL';
const SET_VISIBILITY_FILTER = 'SET_VISIBILITY_FILTER';

export { ADD_TODO, DELETE_TODO, SAVE_TODO, TOGGLE_TODO, TOGGLE_ALL_TODOS, CLEAR_COMPLETED, CLEAR_ALL, SET_VISIBILITY_FILTER }
